USE REPUESTOS;
-- EJERCICIO1 PA que cuente la cantidad de repuestos eléctricos y mecánicos 
-- que se han comprado en una fecha específica.
DELIMITER $$
CREATE PROCEDURE EJ1(IN FECHA1 DATE)
BEGIN
DECLARE CTM FLOAT(6,2);
DECLARE CTE FLOAT(6,2);
SELECT SUM(C.CANTIDAD) INTO CTM
FROM MECANICO M INNER JOIN COMPRA C ON M.CODIGO=C.CODIGO
WHERE DATE(C.FECHA) = FECHA1;

SELECT SUM(C.CANTIDAD) INTO CTE
FROM ELECTRICO E INNER JOIN COMPRA C ON E.CODIGO=C.CODIGO
WHERE DATE(C.FECHA) = FECHA1;

SELECT CTM AS 'CANTIDAD DE REPUESTOS MECANICOS',
		CTE AS 'CANTIDAD DE REPUESTOS ELECTRICOS';
END $$
DELIMITER ;

CALL EJ1('2019-05-05');

SELECT * FROM COMPRA;

-- EJERCICIO2 PA que reciba como parámetro el nombre de un encargado 
-- y muestre todas las entregas que realizó, incluyendo el repuesto 
-- y la cantidad.

DELIMITER $$
CREATE PROCEDURE EJ2(IN NOMEN VARCHAR(50))
BEGIN
DECLARE IEN INT(6);
IF EXISTS(SELECT * FROM ENCARGADO WHERE NOMBRE=NOMEN) THEN

SET IEN = (SELECT ITEM FROM ENCARGADO WHERE NOMBRE = NOMEN);

SELECT R.DESCRIPCION AS 'REPUESTO',
		E.CANTIDADE AS 'CANTIDAD',
        E.FECHAE AS 'FECHA'
FROM REPUESTO R INNER JOIN ENTREGA E ON R.CODIGO=E.CODIGO
WHERE E.ITEM = IEN;
ELSE SELECT 'EL ENCARGADO NO ESTA REGISTADO' AS MENSAJE;
END IF;
END $$
DELIMITER ;

CALL EJ2('VICTOR CASTEDO');
SELECT * FROM ENTREGA;
-- EJERCICIO3 PA que reciba el código de un repuesto y el NIT del 
-- proveedor, y actualice el costo 
-- de esa compra a un nuevo valor introducido por parámetro.
DELIMITER $$
CREATE PROCEDURE EJ3(IN CR CHAR(6), IN NP CHAR(10), IN NC FLOAT(6,2))
BEGIN
IF EXISTS(SELECT * FROM PROVEEDOR WHERE NIT=NP)THEN
IF EXISTS(SELECT * FROM REPUESTO WHERE CODIGO=CR)THEN
UPDATE COMPRA SET COSTO=NC WHERE CODIGO=CR AND NIT=NP;
SELECT * FROM COMPRA WHERE CODIGO=CR AND NIT=NP;
ELSE SELECT 'REPUESTO NO REGISTRADO' AS MENSAJE; END IF;
ELSE SELECT 'PROVEEDOR NO REGISTRADO' AS MENSAJE;
END IF;
END $$
DELIMITER ;
CALL EJ3('R-0001','1011112450',250);
SELECT * FROM COMPRA;

-- EJERCICIO4 PA que reciba dos fechas como parámetros y muestre 
-- todas las compras registradas 
-- dentro de ese rango, calculando para cada una de ellas 
-- el costo total real tomando en cuenta 
-- el costo unitario, la cantidad adquirida, el descuento y 
-- el impuesto aplicados, de manera 
-- que se refleje el valor final pagado en cada operación.
DELIMITER $$
CREATE PROCEDURE EJ4(IN F1 DATE, IN F2 DATE)
BEGIN
DECLARE AUX DATE;
IF(F1>F2) THEN
SET AUX = F1;
SET F1 = F2; 
SET F2 = AUX;	
END IF;
SELECT CODIGO, NIT, FECHA, CANTIDAD,
	(COSTO - DESCUENTO+IMPUESTO) AS 'COSTO', DESCUENTO, IMPUESTO
FROM COMPRA 
WHERE DATE(FECHA) BETWEEN F1 AND F2;
END $$
DELIMITER ;
CALL EJ4('2025-09-30', '2019-05-04');
-- F1 2025-05-05
-- F2 2020-06-06
SELECT * FROM COMPRA;

-- EJERCICIO5 PA que reciba como parámetro un número mínimo y muestre 
-- únicamente a los 
-- proveedores cuya cantidad de compras registradas supere ese valor,
-- permitiendo identificar 
-- a los que tienen mayor participación en las adquisiciones.
DELIMITER $$
CREATE PROCEDURE EJ5(IN CM INT)
BEGIN
SELECT P.NOMBREP AS 'PROVEEDOR',
		COUNT(*) AS 'COMPRAS REGISTRADAS'
FROM PROVEEDOR P INNER JOIN COMPRA C ON P.NIT=C.NIT
GROUP BY P.NOMBREP
HAVING COUNT(*) >= CM;
END $$
DELIMITER ;
CALL EJ5(4);

-- EJERCICIO6 PA que inserte una compra cuando solo se conoce el 
-- nombre del repuesto, el nombre del proveedor,
-- la cantidad y el precio unitario. Use variables locales.
DELIMITER $$
CREATE PROCEDURE EJ6(IN DR VARCHAR(50), IN NP VARCHAR(50), IN CN INT, IN PR FLOAT(6,2))
BEGIN
DECLARE CR CHAR(6);
DECLARE NIP CHAR(10);
IF EXISTS(SELECT * FROM PROVEEDOR WHERE NOMBREP=NP)THEN
IF EXISTS(SELECT * FROM REPUESTO WHERE DESCRIPCION=DR)THEN
SELECT CODIGO INTO CR FROM REPUESTO WHERE DESCRIPCION=DR;
SELECT NIT INTO NIP FROM PROVEEDOR WHERE NOMBREP=NP;
INSERT INTO COMPRA(CODIGO,NIT,FECHA,CANTIDAD,COSTO) VALUES(CR,NIP,NOW(),CN,CN*PR);
SELECT * FROM COMPRA WHERE CODIGO=CR AND NIT=NIP;
ELSE SELECT 'REPUESTO NO REGISTRADO' AS MENSAJE; END IF;
ELSE SELECT 'PROVEEDOR NO REGISTRADO' AS MENSAJE; END IF;
END $$
DELIMITER ;
CALL EJ6('AMORTIGUADOR2','JUAN PABLO RUIZ',5,35.50);
SELECT * FROM REPUESTO;

-- EJERCICIO7 PA que reciba el nombre de un proveedor y dos fechas, 
-- y calcule el total gastado en compras 
-- dentro de ese rango. Use variables locales para almacenar el NIT.
DELIMITER $$
CREATE PROCEDURE EJ7(IN NP VARCHAR(50), IN F1 DATE, IN F2 DATE)
BEGIN
DECLARE AUX DATE;
DECLARE NIP CHAR(10);
IF(F1>F2) THEN
SET AUX = F1;
SET F1 = F2;
SET F2 = AUX;
END IF;
IF EXISTS(SELECT * FROM PROVEEDOR WHERE NOMBREP=NP)THEN
SELECT NIT INTO NIP FROM PROVEEDOR WHERE NOMBREP=NP;
SELECT SUM(COSTO) AS 'COSTO TOTAL'
FROM COMPRA 
WHERE NIT=NIP AND DATE(FECHA) BETWEEN F1 AND F2;
ELSE SELECT 'PROVEEDOR NO REGISTRADO' AS MENSAJE; END IF;
END $$
DELIMITER ;
CALL EJ7('JUAN PABLO RUIZ', '2019-05-05','2025-09-30');
SELECT * FROM COMPRA;
-- EJERCICIO8 PA que muestre los repuestos más comprados en un 
-- rango de fechas, y solo aquellos que superen una cantidad mínima.
DELIMITER $$
CREATE PROCEDURE EJ8(IN F1 DATE, IN F2 DATE, IN CMIN INT)
BEGIN
DECLARE AUX DATE;
IF(F1>F2) THEN
SET AUX = F1;
SET F1 = F2;
SET F2 = AUX;
END IF;
SELECT R.DESCRIPCION AS 'REPUESTO',
		SUM(C.CANTIDAD) AS 'CANTIDAD TOTAL'
FROM REPUESTO R INNER JOIN COMPRA C ON R.CODIGO=C.CODIGO
WHERE DATE(C.FECHA) BETWEEN F1 AND F2
GROUP BY R.DESCRIPCION
HAVING SUM(C.CANTIDAD) >= CMIN;
END $$
DELIMITER ;

CALL EJ8('2019-05-05','2025-09-30',16);

