USE REPUESTOS;

-- EJERCICIO 01: lista de repuestos con costo real entre 150 y 250 Bs.
DELIMITER $$
CREATE PROCEDURE EJ_SP1()
BEGIN
	SELECT R.DESCRIPCION AS 'REPUESTO',
		   P.NOMBREP AS 'PROVEEDOR',
		   (C.COSTO - C.DESCUENTO + C.IMPUESTO) AS 'COSTO REAL Bs.'
	FROM REPUESTO R
		INNER JOIN COMPRA C ON R.CODIGO = C.CODIGO
		INNER JOIN PROVEEDOR P ON C.NIT = P.NIT
	WHERE (C.COSTO - C.DESCUENTO + C.IMPUESTO) BETWEEN 150 AND 250;
END $$
DELIMITER ;

CALL EJ_SP1;

-- EJERCICIO 02: cantidad total entregada por cada encargado.
DELIMITER $$
CREATE PROCEDURE EJ_SP2()
BEGIN
	SELECT E.NOMBRE AS 'ENCARGADO',
		   SUM(EN.CANTIDADE) AS 'TOTAL ENTREGADO'
	FROM ENCARGADO E
		INNER JOIN ENTREGA EN ON E.ITEM = EN.ITEM
	GROUP BY E.NOMBRE
	ORDER BY SUM(EN.CANTIDADE) DESC;
END $$
DELIMITER ;

CALL EJ_SP2;

-- EJERCICIO 03: repuestos electricos con costo promedio de compra.
DELIMITER $$
CREATE PROCEDURE EJ_SP3()
BEGIN
	SELECT R.DESCRIPCION AS 'REPUESTO ELECTRICO',
		   EL.POTENCIA AS 'POTENCIA (W)',
		   AVG(C.COSTO) AS 'COSTO PROMEDIO Bs.'
	FROM REPUESTO R
		INNER JOIN ELECTRICO EL ON R.CODIGO = EL.CODIGO
		INNER JOIN COMPRA C ON R.CODIGO = C.CODIGO
	GROUP BY R.DESCRIPCION, EL.POTENCIA
	HAVING COUNT(*) >= 1;
END $$
DELIMITER ;

CALL EJ_SP3;

-- EJERCICIO 04: proveedores con repuestos cuya descripcion termina en vocal.
DELIMITER $$
CREATE PROCEDURE EJ_SP4()
BEGIN
	SELECT P.NOMBREP AS 'PROVEEDOR',
		   R.DESCRIPCION AS 'REPUESTO',
		   SUM(C.CANTIDAD) AS 'CANTIDAD TOTAL'
	FROM PROVEEDOR P
		INNER JOIN COMPRA C ON P.NIT = C.NIT
		INNER JOIN REPUESTO R ON C.CODIGO = R.CODIGO
	WHERE R.DESCRIPCION LIKE '%A'
	   OR R.DESCRIPCION LIKE '%E'
	   OR R.DESCRIPCION LIKE '%I'
	   OR R.DESCRIPCION LIKE '%O'
	   OR R.DESCRIPCION LIKE '%U'
	GROUP BY P.NOMBREP, R.DESCRIPCION
	ORDER BY P.NOMBREP ASC;
END $$
DELIMITER ;

CALL EJ_SP4;

-- EJERCICIO 05: repuestos con cantidad comprada superior al promedio general.
DELIMITER $$
CREATE PROCEDURE EJ_SP5()
BEGIN
	DECLARE CPRO FLOAT;

	SELECT AVG(CANTIDAD) INTO CPRO FROM COMPRA;

	SELECT R.DESCRIPCION AS 'REPUESTO',
		   P.NOMBREP AS 'PROVEEDOR',
		   SUM(C.CANTIDAD) AS 'CANTIDAD TOTAL'
	FROM REPUESTO R
		INNER JOIN COMPRA C ON R.CODIGO = C.CODIGO
		INNER JOIN PROVEEDOR P ON C.NIT = P.NIT
	GROUP BY R.DESCRIPCION, P.NOMBREP
	HAVING SUM(C.CANTIDAD) > CPRO;
END $$
DELIMITER ;

CALL EJ_SP5;
